#Fri Apr 12 08:33:56 UTC 2024
micronaut:
  application:
    name: core-application

rabbitmq:
  uri: amqp://localhost:5672
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  exchange:
    insee:
      sirene: sirene
  queue:
    insee:
      sirene-search: sirene.search.q
  binding:
    insee:
      sirene-search: sirene.search.b